POST http://localhost:9000/login
Content-Type: application/json

{
    "email": "emilysmith@outmail.com",
    "password": "password"
}

###

GET http://localhost:9000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW1pbHlzbWl0aEBvdXRtYWlsLmNvbSIsImlhdCI6MTcwNjA3Njg2N30.bcOPXf_jjwXoIGYkUjosP8rH3Rq1m4fbVB06HPy-YL0

###

GET http://localhost:9000/auth
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW1pbHlzbWl0aEBvdXRtYWlsLmNvbSIsImlhdCI6MTcwNjA3Njg2N30.bcOPXf_jjwXoIGYkUjosP8rH3Rq1m4fbVB06HPy-YL0

###
POST http://localhost:9000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9iIiwiaWF0IjoxNzA1ODEyOTAyLCJleHAiOjE3MDU4MTM1MDJ9.tSNqevCasMacKKYIiVDG41GQYwaEQDCnKKcmMmUai1c"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9iIiwiaWF0IjoxNzA1ODEzNDgwLCJleHAiOjE3MDU4MTQwODB9.KG371qJDPtk0IU_L9p_UKWQTeHm5fbyBhkFMZPJ3maE"
}
